### ISSUE TITLE
Add cosmetic perks for Glimesh Platform Subscriptions

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#110]
There's two levels of Platform Subscribers on Glimesh, both are completely optional to get the Glimesh experience. We need to figure out the kind of perks we want both to have, any opinions are welcome!

**Glimesh Supporter**
* Colored Avatar Ring in all chats
* Allowed usage of global animated emotes 

**Glimesh Founder**
* All Supporter Perks
* Founder Badge or Username Color?
* Animated Avatar Ring
* Custom uploaded emotes

**Comment by Heiwa1580** [comment]
Idea for Founder but adding a Pretzel Rocks account or Trial to go along with the founder package

**Comment by Heiwa1580** [comment]
774269164725469224 - Discord Message ID

Maybe allow the user to upload animated gifs if they are a platform subscriber like discord nitro?
