### ISSUE TITLE
Custom rules entry for streams

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#113]

**Comment by mja00** [comment]
Should be easy enough. Will just steal your profile description code. :)

**Comment by clone1018** [comment]
@mja00 I'm going to make a quick management page for streamers so we can add more static content like this, + moderation, logs, etc. You might want to wait until that is done.

**Comment by mja00** [comment]
👌

**Comment by Cykotiq** [comment]
I think ideally this would be a pop-over on the chat box you would have to agree to the first time you enter the chat, before you can type in chat, not just another profile panel
