### ISSUE TITLE
Add blog

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#17]
I can be convinced this doesn't fit into Glimesh, but I want to blog about our recent streaming success & help drive traffic to the site.

**Comment by mja00** [comment]
Maybe use [Medium ](https://medium.com/creators) for this, that way it already has a large audience plus money can be made off the blog with literally no effort.

**Comment by Zaeo** [comment]
I feel Blog integration wouldn't be all that difficult. Simply install Wordpress to a subdomain, like blog.glimesh.tv/

- Mr Goodhand.
