### ISSUE TITLE
Internationalization! 

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#21]
We must support other languages! Part of the scope of this ticket is figuring out how custom languages work with Phoenix.

**Comment by omn0mn0m** [comment]
Good starting point: https://hexdocs.pm/gettext/Gettext.html

**Comment by mja00** [comment]
Going to look into gettext and everything related to it. Expect this to take a while as I want to make sure everything is 100% before having people put work into translations.
