### ISSUE TITLE
Login with Twitter

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#23]
Should allow for Twitter as a social login that users can use to get started a bit quicker. This should also replace the current "type in your username" method.

**Comment by omn0mn0m** [comment]
Relevant Twitter Documentation: https://developer.twitter.com/en/docs/basics/authentication/guides/log-in-with-twitter

**Comment by Zaeo** [comment]
I'd also consider Google logins, as I tend to use those login credentials where possible.

**Comment by clone1018** [comment]
Not super interested in social logins at this point, will revisit in the future.
