### ISSUE TITLE
Usernames are case sensitive 

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#25]
Currently https://glimesh.tv/ClOnE1018/profile does not resolve my profile. We'll probably need to either slugify all usernames, or ensure `where` statement searches independent of the case.

**Comment by TortleWortle** [comment]
I believe Twitch has a `displayname` and `username` where username is basically behaves like a slug, but you can change your `displayname` to be any combination of capitals of your `username`.

**Comment by mja00** [comment]
This is exactly how twitch does it. You can change the capitalization but only the username is used in API calls and such.

**Comment by mja00** [comment]
Could just rename the username field to displayname here and then copy + lowercase all displaynames to fill the username.
