### ISSUE TITLE
Chat: Emote picker and settings buttons stop responding to clicks

### ISSUE THREAD

**Issue by moltenllama** [Glimesh/glimesh.tv#267]
What are the steps to reproduce this issue?
-------------------------------------------
1. Go to any channel
2. Type anything in the chat message box, then backspace so it's blank.  A cannot be blank error appears.

What happens?
-------------
The emote picker and settings menus stop responding to clicks.  Even if you then type something new in the chat message box, the cannot be blank error disappears as expected, but the buttons still don't respond.

What were you expecting to happen?
----------------------------------
The emote picker and settings menus should popup their respective menus when clicked.

Any logs, error output, etc?
----------------------------
NIL

Any other comments?
-------------------
NIL

What versions of software are you using?
----------------------------------------
**Operating System:** Windows 10 Pro (2004).  Build 19041.630

**Browser:** Google Chrome 86.0.4240.198 (Official Build) (64-bit)

**Comment by clone1018** [comment]
@moltenllama We released a fix for this, can you confirm if it is still being weird for you?

**Comment by moltenllama** [comment]
Issue has been resolved. 

Thanks :)
