### ISSUE TITLE
Emotes Text are not cleared when a space is entered after the emote command

### ISSUE THREAD

**Issue by Heiwa1580** [Glimesh/glimesh.tv#287]
https://discord.com/channels/727111257953402891/735559059432013956/785592725822373938

Emotes are not removing the text after they are sent if they have a space after them. This can allow a user to hold enter and spam emotes at a very quick rate.

**Comment by clone1018** [comment]
Fixed in https://github.com/Glimesh/glimesh.tv/pull/300
