### ISSUE TITLE
Followers Page Does Not Match with users

### ISSUE THREAD

**Issue by KruxGamingTV** [Glimesh/glimesh.tv#320]
On the followers page we should fix it like the users page images attached for preview. But this is just a cosmetic fix so people see that we are serious about what we do.

Needs Fix On Followers Page: 

<img width="501" alt="Screen Shot 2020-12-24 at 5 04 57 PM" src="https://user-images.githubusercontent.com/76572424/103107521-12459000-460d-11eb-979b-ff988d8085f5.png">

Correct Way:

<img width="501" alt="Screen Shot 2020-12-24 at 5 26 26 PM" src="https://user-images.githubusercontent.com/76572424/103107538-43be5b80-460d-11eb-8e3b-ff758b475b44.png">

**Comment by KruxGamingTV** [comment]
<img width="739" alt="Screen Shot 2020-12-24 at 8 36 16 PM" src="https://user-images.githubusercontent.com/76572424/103113308-29de4200-4628-11eb-9ae1-48edbfdc5ba8.png">

Not sure but this may have fixed the issue that I have brought up.

**Comment by KruxGamingTV** [comment]
So possibly put a limit on how many characters can be in the username would fix the issue but I am working on trying to make the cards bigger like the user page.

**Comment by mja00** [comment]
Fixed in a previous merge.
