### ISSUE TITLE
Allow GCT to see stream metadata for diagnosing issues

### ISSUE THREAD

**Issue by tjcasey** [Glimesh/glimesh.tv#336]
As a GCT member I'd like to be able to see a user's stream metadata to help investigate technical issues reported.  Details could include things like:

- Date/Time stream started (and timezone or display it relative time eg. '4 minutes ago'
- Bitrate used
- Ingest used
- Length of stream
- Anything else that gets logged like errors

This could be presented on the GCT dash as a table showing the last 5 streams.  Could then maybe click on each stream to see further in depth details or logs?

**Comment by clone1018** [comment]
It'll be easiest to do this after we have some basic channel analytics for streamers. Currently the metadata is very noisy!

**Comment by clone1018** [comment]
We do have this on production!
