### ISSUE TITLE
Channel Settings: Internal Server Error when atttempting to upload images over the 100KB limit

### ISSUE THREAD

**Issue by moltenllama** [Glimesh/glimesh.tv#366]
Steps:
- As a logged in user, visit your Channel Settings page.
- Click the Browse button next to either Chat Background or Channel Poster
- Select a file that is over 100KB in size
- Click Update Channel button to save

Expected:
- An error message should appear stating the filesize limit and that the upload was too large

Actual:
- Internal Server Error

**Comment by mja00** [comment]
Looks to be an issue unrelated to the channel background, looks like when updating the channel it re-renders the view but without a needed launched assign that is used. Looking into a fix now.
