### ISSUE TITLE
Stream key shown to user should include channel prefix

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#370]
Current format:
`<stream_key>`

Correct format: 
`<channel_id>-<stream_key>`

Locations:
- [ ] API
- [ ] UI on stream page

**Comment by mja00** [comment]
From the first PR for this (https://github.com/Glimesh/glimesh.tv/pull/372#issuecomment-758261797): 
1. Rename existing field to hmackey
2. Adjust API to return both hmackey & stream key
3. Concatenate the values for the frontend (or better yet created a shared function)
4. Ignore me and do what feels right
