### ISSUE TITLE
DNS:  Update SPF record for glimesh.tv to include shopify

### ISSUE THREAD

**Issue by moltenllama** [Glimesh/glimesh.tv#447]
Emails from the Glimesh Shop are softfailing SPF checks.

```
Received: from smtp2.shopify.com (smtp2.shopify.com. [104.196.215.101])
        by mx.google.com with ESMTPS id e8si2003454vsr.13.2021.02.05.16.44.30
        for <xxxxx@gmail.com>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 05 Feb 2021 16:44:30 -0800 (PST)
**Received-SPF: softfail (google.com: domain of transitioning support@glimesh.tv does not designate 104.196.215.101 as permitted sender) client-ip=104.196.215.101;**
```

We should update our domain SPF record to include the shopify IP ranges to increase the likelihood of our emails being delivered straight to inboxes rather than junk/promotional.  There's also a duplicate entry for eoidentity.com which can be removed.

Old:
v=spf1 include:31d956bd10.arborescens.eoidentity.com include:spf.messagingengine.com include:31d956bd10.arborescens.eoidentity.com include:mailgun.org ~all

New:
v=spf1 include:shops.shopify.com include:31d956bd10.arborescens.eoidentity.com include:spf.messagingengine.com  include:mailgun.org ~all

**Comment by clone1018** [comment]
Thanks, added this SPF, removed the duplicate.

Also added the cname's shopify required to authenticate the domain.

**Comment by clone1018** [comment]
![image](https://user-images.githubusercontent.com/226638/107771892-76c9c500-6d09-11eb-8b01-adb42cda9659.png)

**Comment by clone1018** [comment]
![image](https://user-images.githubusercontent.com/226638/107777927-759c9600-6d11-11eb-9f15-8126ed96a2bc.png)
