### ISSUE TITLE
chat settings menu doesn't open reliably

### ISSUE THREAD

**Issue by Cykotiq** [Glimesh/glimesh.tv#455]
some users have reported that when they click the chat settings gear it does not open the menu, but instead works like and anchor tag, scrolling them to the top of the page. Refreshing the page seems to fix the issue, and the button works properly without scrolling

**Comment by mja00** [comment]
Looks to be an issue with liveview. When swapping between liveview pages the DOM is never reloaded. Investigating.

**Comment by Cykotiq** [comment]
steps to reproduce:
load new tab to glimesh.tv
click tech
click glimovies
click chat settings gear
