### ISSUE TITLE
Clicking "Deny" on 0auth does nothing

### ISSUE THREAD

**Issue by Cykotiq** [Glimesh/glimesh.tv#467]
Clicking "Deny" on oauth permissions page should return you to the developers website/app to receive an 0auth failed message

**Comment by mja00** [comment]
Currently it does redirect back to the callback specified in the authorization request with `?error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request.` tacked onto the end.

If you can provide a video of the behavior you're currently experiencing.

**Comment by Cykotiq** [comment]
> Currently it does redirect back to the callback specified in the authorization request with `?error=access_denied&error_description=The+resource+owner+or+authorization+server+denied+the+request.` tacked onto the end.
> 
> If you can provide a video of the behavior you're currently experiencing.

it appears to have been fixed

**Comment by mja00** [comment]
Closing the issue in that case.
