### ISSUE TITLE
On non-HTTPS, stream key "click to copy" button doesn't copy anything

### ISSUE THREAD

**Issue by haydenmc** [Glimesh/glimesh.tv#496]
0. Connect to a glimesh.tv instance on HTTP (not HTTPS)
1. Open Channel Settings
2. Click "Click to Copy" button next to stream key
3. Attempt to paste copied key into text editor

Expect: Stream key as displayed is pasted
Actual: Nothing is pasted (or my previous clipboard value is pasted)

Looks like a JS error occurs:
```
stream:390 Uncaught TypeError: Cannot read property 'writeText' of undefined
    at HTMLButtonElement.<anonymous> (stream:390)
```
![Screenshot of faulting source line](https://user-images.githubusercontent.com/5422053/109291805-480a1f00-77de-11eb-8326-426695c65401.png)

**Comment by clone1018** [comment]
Which browser are you using @haydenmc ?

**Comment by haydenmc** [comment]
This was msedge 88.0.705.74.

This was late last night but now that I think about it, this may have been in an incognito/private-mode window, so perhaps that limits access to the clipboard API.

**Comment by haydenmc** [comment]
Turns out it's because my local dev instance was running unsecured!

https://stackoverflow.com/a/51823007/2874534

It would be nice if we checked the navigator.clipboard property and presented an error if it's not available - but probably relatively low priority since this'll never hit in production.

**Comment by clone1018** [comment]
I was thinking we might want to just quietly delete the button if we cannot access the API for it.

**Comment by haydenmc** [comment]
Even better!
