### ISSUE TITLE
🎥 Video Streaming Infrastructure

### ISSUE THREAD

**Issue by haydenmc** [Glimesh/glimesh.tv#50]
I'm starting this issue to track and discuss the approach for the video streaming infrastructure behind Glimesh.

AKA, how do the bits get from the streamer's OBS instance to an ingest server to the viewer's browser?

Today, for demo streams, we are utilizing [OvenMediaEngine](https://github.com/AirenSoft/OvenMediaEngine)'s fantastic software, which allows for RTMP ingest, routing from origin server to various edge servers, and playback via WebRTC in the browser. The latency is impressive, but still a tad above 1 second. I suspect this is at least in part due to the RTMP protocol used to transmit from OBS to the OME Origin server. Unlike FTL, RTMP utilizes TCP transport, which introduces some additional latency in order to guarantee delivery of packets and packet ordering. 

FTL utilized a UDP transport, which does not guarantee packet delivery or packet ordering, but operates at maximum speed. This is the transport utilized by most real-time applications (gaming, audio/video chat, etc.) 

A quick test utilizing [Janus WebRTC gateway](https://github.com/meetecho/janus-gateway) with an RTP (UDP-based) ingest showed some very promising latency (disclaimers being that this is 1 viewer, no load balancing, Seattle<->SFO connection):

![Janus RTP latency test](https://user-images.githubusercontent.com/5422053/89110253-c431b500-d3fd-11ea-8722-1f62ccd53295.png)

It may be possible to create a Janus plugin to accept FTL connections and use this to ingest streams on a UDP transport - effectively what Mixer was doing. This also means that the existing FTL output plugins on OBS would be supported, so streamers wouldn't need to use any additional software to enjoy low latency streaming on Glimesh. Currently investigating this option!

**Comment by haydenmc** [comment]
Alright, so far I've got a good understanding of how the FTL ingest "control" protocol works, and I've documented that here:

https://github.com/Glimesh/glimesh.tv/wiki/FTL-Engineering-Notes

I hacked together a rogue ingest control server here that is able to accept connections and get FTL clients to start sending media data.

https://github.com/haydenmc/FtlIngest

The next step is figuring out how to route that media data through Janus to get a WebRTC stream going end-to-end.

**Comment by haydenmc** [comment]
Had the first successful FTL transmission through Janus tonight!

![FTL transmitting video to a browser via Janus WebRTC](https://user-images.githubusercontent.com/5422053/89151989-03075e00-d517-11ea-8fbc-a92213b12196.png)

FTL's media transport protocol is essentially RTP but breaking [some rules](https://tools.ietf.org/html/rfc3550#page-17). I was able to get the built-in Janus RTP plugin to accept FTL packets by having it blindly accept all packets as video (no audio at the moment). I will document this more later.

The next step is to develop a Real™ FTL plugin for Janus that is less hacky, and will allow for full streaming, audio included.

**Comment by clone1018** [comment]
We did launch https://github.com/Glimesh/janus-ftl-plugin/
