### ISSUE TITLE
Add Captcha system to registration page

### ISSUE THREAD

**Issue by mja00** [Glimesh/glimesh.tv#51]
Add reCaptcha(or equivalent) to the registration page to stop bots from registering a bunch of accounts.

**Comment by clone1018** [comment]
We'll need to find a privacy conscious vendor for this. Google products aren't really ideal for Glimesh.

**Comment by mja00** [comment]
hCaptcha is quite good for privacy and actually works somewhat better.

**Comment by Heiwa1580** [comment]
I got part of this done but I can't find an editor on mobile that will allow me to do the rest of the backend stuff...

**Comment by clone1018** [comment]
This is done in https://github.com/Glimesh/glimesh.tv/pull/210
