### ISSUE TITLE
Audio on Chromium based browsers is muxed to mono

### ISSUE THREAD

**Issue by DerpyChap** [Glimesh/glimesh.tv#535]
This appears to be a bug in Chromium relating to OPUS audio and WebRTC (based on this open issue: https://bugs.chromium.org/p/webrtc/issues/detail?id=8133) and is not present in Firefox.

I recorded a demonstration of the issue here: https://youtu.be/8EfQdcGzsu8

Tested on the latest versions of Chrome Canary, Stable and Microsoft Edge along with Chromium itself.

It might be possible to work around this issue, seeing as though Discord is capable of playing back stereo OPUS through WebRTC, but I'm in no way qualified enough to provide a solution. :P

**Comment by haydenmc** [comment]
Howdy! Great find!

Looks like this is due to how we do our SDP negotiation. I've opened an issue against our WebRTC/FTL repo to track this problem here:
https://github.com/Glimesh/janus-ftl-plugin/issues/98
