### ISSUE TITLE
climchu / climcoffee emote typos

### ISSUE THREAD

**Issue by LukeHandle** [Glimesh/glimesh.tv#554]
A few users have reported, but the 2 emotes likely should be "glim" vs. "clim":

https://github.com/Glimesh/glimesh.tv/blob/2d4273bdee51b750816e3ecb085d10c491e092c6/config/emotes.exs#L5-L6

**Comment by Heiwa1580** [comment]
Some of these has been fixed. I couldn't figure out how to fix the .png's

**Comment by clone1018** [comment]
Resolved in the repo, will deploy soon.
