### ISSUE TITLE
Websocket based firehose API

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#57]
Should include:

* Follows
* Chats
* Subscriptions

**Comment by mja00** [comment]
Could also use [SSE](https://en.wikipedia.org/wiki/Server-sent_events) for this. Pretty much just fling data at a url and have the client read and handle it. No need for keeping a connection up or using any standards other than HTTP.

**Comment by haydenmc** [comment]
SSE is worth considering but there are a couple notable limitations:

Services would have to make separate requests to send data back to Glimesh, which can be a little extra hurdle and a source of latency if bots or services want to respond quickly to events they're listening for.

Apparently there's a pretty strict [connection limit with the EventSource API](https://bugzilla.mozilla.org/show_bug.cgi?id=906896) in Chromium and Firefox as well, which was marked won't fix.

I lean mostly toward web sockets as they seem to be the 'de facto' standard for real-time web APIs - they've been embraced by a lot of services and are familiar to many of the developers working in this space.

**Comment by clone1018** [comment]
Some initial work completed on this, next up is to add subscriptions.

https://github.com/Glimesh/glimesh.tv/pull/121

**Comment by clone1018** [comment]
Added in this PR: https://github.com/Glimesh/glimesh.tv/pull/173

Current unusable until we get cross_origin disabled in Phoenix.

**Comment by clone1018** [comment]
Usable since https://github.com/Glimesh/glimesh.tv/pull/184
