### ISSUE TITLE
Opt out of privacy invasive FLoC tracking from Google

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#621]
re: https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network

Looks like a simple header is needed to tell it to fuck off.

**Comment by clone1018** [comment]
Also: https://plausible.io/blog/google-floc

**Comment by cactysman** [comment]
You guys are aware, that FLoC is opt-in, right? No need to put on a tinfoil hat, just because it's Google testing something.

https://twitter.com/Log3overLog2/status/1384337637763387394

**Comment by clone1018** [comment]
I read that same thread, I think generally though we want to make it clear that we do not support our users privacy being compromised. 

From my perspective there's no risk in including the header since it does specifically opt us out (even if we include some ad network that triggers it).

**Comment by clone1018** [comment]
GitHub took similar action here: https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/
