### ISSUE TITLE
Improve docker-compose development experience

### ISSUE THREAD

**Issue by Eein** [Glimesh/glimesh.tv#632]
Issue: Docker compose can be used to bootstrap the project and make developing new features easier but is being underutilized

The intent of this issue is a placeholder for discussion around some changes I'll be putting forward.

Should solve:
- development experience for dev and test to create features more easily
- maintain as much parity with production as possible
- remove setup requirements, and use sensible defaults with overrides
- make using dependency injection for mocks in test much easier
- documentation around booting up a development environment
- should be able to start compose and get a full suite of passing tests

Gotchas:
- current development/staging server is deploying using the `docker-compose.yml` - this will need to be moved to `docker-compose.prod.yml` using production-like credentials/env

References https://github.com/Glimesh/glimesh.tv/pull/633

**Comment by Eein** [comment]
no-config docker-compose is done! tests run!
![image](https://user-images.githubusercontent.com/5025835/115127599-8d4fff00-9f8c-11eb-874b-f2c730706310.png)

**Comment by Eein** [comment]
What version of postgresql is used in production - it would be a good idea to match parity on this in the docker-compose file in case a new feature is attempted to be used in development?

**Comment by LukeHandle** [comment]
> What version of postgresql is used in production - it would be a good idea to match parity on this in the docker-compose file in case a new feature is attempted to be used in development?

Based on the Terrraform, looks like 12
https://github.com/Glimesh/ops/blob/f170b96e753741b1479af3d20804c6a78e36fc39/terraform/web.tf#L14

**Comment by mja00** [comment]
As requested by @Eein, after running `mix compile --force --profile time`, my results can be found in [this](https://pastebin.com/0TRB9FzK) pastebin.

**Comment by Eein** [comment]
Closing this issue - as discussion will be isolated towards #646
