### ISSUE TITLE
Don't call the Twitter API until the user requests it

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#634]
Currently we poke the Twitter API every single time someone requests any of the pages under UserSettingsController. 

https://github.com/Glimesh/glimesh.tv/blob/dev/lib/glimesh_web/controllers/user_settings_controller.ex#L136

Ideally we should hide expensive requests like this behind an initial user opt in to generate the link. The same would apply for TaxIDPro Form Link & Stripe Account Link.

**Comment by clone1018** [comment]
This caused downtime on Friday due to the Twitter API timing out before the page could load for the user.

**Comment by Eein** [comment]
Did an initial check - what should likely happen here is that a route is provided to handle the creation of the authorize URLs.

For context on anyone looking to tackle this issue:

How Ueberauth and omniauth in ruby (some other packages) do it is to provide an /auth/twitter (or any other alternative) route on the site that handles most of the behaviour located here:
https://github.com/glimesh/glimesh.tv/blob/dev/lib/glimesh/socials/twitter.ex#L29

The flow would look like

1. GET /auth/twitter
2. redirect to the authorize_url returned by socials/twitter.ex (above)

**Comment by clone1018** [comment]
Solved in #904
