### ISSUE TITLE
Default admin access

### ISSUE THREAD

**Issue by codingtip** [Glimesh/glimesh.tv#641]
Hello,

Please, what is default admin access? I have installed glimesh.tv on ubuntu 18, but I can't access admin panel.

Regards.

CT.

**Comment by clone1018** [comment]
Hi there, no such "admin panel" exists. You can find a myriad of tools available in the router.ex file here: https://github.com/Glimesh/glimesh.tv/blob/5c4ef030806bc1ddcc2b23528bbd5cf94d9f17ae/lib/glimesh_web/router.ex#L141-L165 and here: https://github.com/Glimesh/glimesh.tv/blob/5c4ef030806bc1ddcc2b23528bbd5cf94d9f17ae/lib/glimesh_web/router.ex#L167-L196

You can make a user an admin by setting `admin = true` in the database.

**Comment by codingtip** [comment]
Hello,

Thanks, it works for me.

Regards,

CT

**Comment by codingtip** [comment]
Hello,

Please, I can access /admin/categories and /admin/tags as admin but not the /admin/blog

Regards,

CT

**Comment by MechanisM** [comment]
@codingtip glimesh moved their blog away from this repo, afaik now it's just Hugo-powered blog

**Comment by clone1018** [comment]
That's correct, the blog foundation code still exists, but is scheduled to be removed for less surface area.

The problem you are experiencing @codingtip is that there's no /admin/blog route, just /admin/blog/new and the others listed above.

**Comment by codingtip** [comment]
Hello,

Please, can't access the blog at this route: /admin/blog/new

Regards,

CT

**Comment by clone1018** [comment]
What are you getting? Are you an admin?

**Comment by codingtip** [comment]
Hello,

Yes, I'm admin. Please, below is the screenshot:

![image](https://user-images.githubusercontent.com/64996811/115911774-6733ce80-a466-11eb-9a46-808c4e10fa55.png)
