### ISSUE TITLE
Some metrics are not being reported to AppSignal

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#651]
We're having some performance issues on the `startStream` and (potentially) `endStream` functions of the API. We've been trying to track the performance of these for awhile, first using the [decorators](https://docs.appsignal.com/elixir/instrumentation/instrumentation.html#function-decorators) and now the more functional API.

https://github.com/Glimesh/glimesh.tv/blob/042d9c7743b6c9fff4b29aa8d552da2a19989903/lib/glimesh/graphql/resolvers/channel_resolver.ex#L63-L76

We have decorators still in use as well in the Chat Resolver.
https://github.com/Glimesh/glimesh.tv/blob/042d9c7743b6c9fff4b29aa8d552da2a19989903/lib/glimesh/graphql/resolvers/chat_resolver.ex#L10-L23

and it _does_ look like we're getting consistent data for it:
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/226638/115640922-0bdad280-a2e6-11eb-8e4a-006a7761d213.png">

**Comment by clone1018** [comment]
It's worth nothing the currently deployed code for `startStream` is:

https://github.com/Glimesh/glimesh.tv/blob/74e0f86c2e2701fdb04c3c6834223877d91f7eca/lib/glimesh/graphql/resolvers/channel_resolver.ex#L64-L77

**Comment by Eein** [comment]
Hello!

I split up `Glimesh.Streams.start_stream/1` into a few functions, which i gave decorated transaction_events - it doesn't seem like theres alot going on here thats causing many issues.

I think the main thing to note is you will have to start the actual transaction using `@decorate transaction()` when in non phoenix code. The Appsignal Phoenix helper does some magic with the endpoint.ex

![image](https://user-images.githubusercontent.com/5025835/115667948-4a2ebc80-a2fb-11eb-941a-ff736ab09edb.png)
