### ISSUE TITLE
Rename cancel link on the payments page

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#683]
Currently our payments page shows a dangeous red button that makes the user think they can cancel the subscription from that page. In reality they must visit the channel page to unsubscribe, and the button on the payments page is merely a link to the channel.

![image](https://user-images.githubusercontent.com/226638/118399851-18c0bc80-b62d-11eb-92c1-c4054e158f0c.png)

We should either:
a) Make this a normal button, with better text. Something like "go to channel page to unsubscribe" 
b) Make it a functional unsubscribe button.

**Comment by Eein** [comment]
From an end user - i think for business cases it would be better to extract unsubscribe functionality to a new module, and also add a form that lets the business know why they're unsubscribing. 

For example:
- [ ] No longer have the funds (or an answer thats less abrasive)
- [ ] No longer interested in this channel
- [ ] Just wanted to subscribe for a month
- [ ] Abuse (or some other less abrasive answer)
- [ ] Other (no input or no input at all)

It will direct you to a better reasoning path for a why if necessary

**Comment by ChalkLive** [comment]
I can absolutely see how this would cause confusion for the end user. My personal preference here (even though its more work) would be option B as its just easier for the end user to do what they want to do without navigating to more pages, but also allows us to add in a form as said above. That can be a great way to get feedback about why people are unsubscribing.
