### ISSUE TITLE
Add auth / load balancing layer microservice ahead of OME

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh.tv#72]
OvenMediaEngine has been a great software that has successfully hosted numerous streams for Glimesh. However there are a couple of mis-fits of our product's requirements. 

1. No authentication support
    There's preliminary support for signed keys, https://github.com/AirenSoft/OvenMediaEngine/issues/68 but the implementation is not entirely clear yet. 
2. No native load balancing between origins / clients
    Need some mechanism for load balancing clients geographically and based on load. 

I'm proposing we create a middleware microservice to handle the authentication handshake based on the stream key, and locate the streamer geographically. The ideal state is then the microservice just proxies packets directly to OME. 

![Untitled Diagram](https://user-images.githubusercontent.com/226638/89474455-af358880-d753-11ea-9f9f-967e52fe7238.png)

**Comment by enixlabs** [comment]
Coming from an engineers prospective, one of the biggest issues I've come across with client systems, is no offline handshake. Initially you should only require the authentication to be allowed, therefore you can store all user data via an offline Auth server and so create a separate layer away from the full system.  One this protects data, you would then pass data to a second system which handles everything with the user system. A lot of this can be done very easy, especially with the HTTP handshake, as once authenticated, it's stored within your headers (make sure to scrub headers on leaving the site), as that is also another issue and from a security point, users shouldn't be keeping themselves logged in.

**Comment by enixlabs** [comment]
Oh and a offsite system, in terms of hardware, would cost you as little as a couple of hundred pound or Euro. Damn, you could even use a solution like us and it's a old pc used as a data server.

**Comment by clone1018** [comment]
Closing in favor of FTL
