### ISSUE TITLE
Following / Follower routes should paginate / lazyload

### ISSUE THREAD

**Issue by LukeHandle** [Glimesh/glimesh.tv#726]
From looking at PromEx metrics, I've seen some spikes in Phoenix HTTP request times.

Both of these routes are sized based on the count of users or followers:
* `/:username/profile/followers`
* `/:username/profile/following`

For users with a high number they are following (eg. 480+) I've seen request times taking ~7 seconds. This is reflected in the user experience as well with a high TTFB. It's similar when looking at your followers (~360) with a slow page load.

This further causes 100s of avatar requests all at once which isn't ideal.

It seems these pages should behave more like the user list page where the listing is lazy loaded as your scroll. This would improve the load performance I expect?

![image](https://user-images.githubusercontent.com/799079/124394400-45bd5180-dcf7-11eb-897f-4807cc274310.png)

**Comment by clone1018** [comment]
Here's how we lazy load the user search page: https://github.com/Glimesh/glimesh.tv/blob/dev/lib/glimesh_web/live/user_live/index.ex

**Comment by mja00** [comment]
I wanna get back into development so I *think* I'll take this for myself, should be good enough for me to get back into the swing of things.
