### ISSUE TITLE
Refresh token removes scope

### ISSUE THREAD

**Issue by zaccolley** [Glimesh/glimesh.tv#744]
When refreshing a access token the scopes seem to be removed.

Steps to replicate:

1. Create a access token with a scope
2. Refresh the token, returns with scope as `null`
3. Scopes no longer authorised

**Comment by clone1018** [comment]
Created a bug in Boruta: https://gitlab.com/patatoid/boruta_auth/-/issues/12

**Comment by zaccolley** [comment]
So a work around is to make sure to send through a `scope` to the refresh token endpoint with the same scopes as you initial requested.

This will need to be fixed even without this workaround as @clone1018 suggests it doesn't match the RFC for Oauth(?)

**Comment by zaccolley** [comment]
Can confirm this is fixed.
