### ISSUE TITLE
docker erlexec not found

### ISSUE THREAD

**Issue by iznotek** [Glimesh/glimesh.tv#824]
hye, trying to simply build docker prod image i got the following error at run time:
`/app/releases/0.1.0/../../erts-12.2/bin/erl: exec: line 12: /app/erts-12.2/bin/erlexec: not found`
any idea ?
or mistake i made ?

just an simple:
` dpcker build -t myorg/glimesh:latest .`
then update the docker-compose prod with a db, adapting env and image name with the one built.
thanks all

**Comment by clone1018** [comment]
Sorry about that, can you try switching to this branch and seeing if it works for you? https://github.com/Glimesh/glimesh.tv/pull/826

**Comment by iznotek** [comment]
thanks, i made few change

librsvg2-bin instead of librsvg
nobody:nogroup instead of nobody:nobody

also i tried to adapt it to ecto.setup for the database before start
but i still have pb for now... is there a formal way to ecto.setup the db by docker ?

```
FROM elixir:1.13.4-slim AS app
RUN apt-get update
RUN apt-get install -y --no-install-recommends libssl-dev libncurses-dev ca-certificates imagemagick librsvg2-bin npm

RUN npm install -g svgo

WORKDIR /app
RUN mix local.hex --force && \
    mix local.rebar --force

RUN chown nobody:nogroup /app
USER nobody:nogroup

COPY --from=build --chown=nobody:nogroup /app/_build/prod/rel/glimesh ./
COPY --from=build --chown=nobody:nogroup /app/priv ./priv
COPY --from=build --chown=nobody:nogroup /app/config ./config
COPY --from=build --chown=nobody:nogroup /app/mix.exs ./mix.exs
COPY --from=build --chown=nobody:nogroup /app/mix.lock ./mix.lock

ENV HOME=/app

RUN ls /app
RUN ls /app/erts-12.3.1/bin/

CMD ["sh", "-c", "mix ecto.setup && bin/glimesh start"]
```

**Comment by clone1018** [comment]
I don't use Docker locally usually, I'll work on getting the build working and then push my changes up!

**Comment by clone1018** [comment]
Okay, I've got the working Dockerfile pushed to the main `dev` branch. I also ran `docker-compose up` per the docs and that creates the DB and sets everything up for you. Let me know if that works!

**Comment by clone1018** [comment]
We use docker for our production deploys now, so please let me know if this isn't working for you by creating a new issue.
