### ISSUE TITLE
prod.exs config issue 

### ISSUE THREAD

**Issue by 4563453** [Glimesh/glimesh.tv#842]
Hello Guys, 

I try to setup glimesh app with https on docker.
I change prod.exs to this config

> import Config

config :logger, level: :info
config :glimesh, GlimeshWeb.Endpoint, 
  url: [host: "myname.mydomain.org", port: 8444],
       https: [
         port: 8444,
         cipher_suite: :strong,
         keyfile: System.get_env("ssl/privkey.pem"),
         certfile: System.get_env("ssl/fullchain.pem"),
         transport_options: [socket_opts: [:inet6]]
       ]

config :glimesh, GlimeshWeb.Endpoint, force_ssl: [hsts: true]

get this error:

warning: variable "config" does not exist and is being expanded to "config()", please use parentheses to remove the ambiguity or change the variable name
  config/prod.exs:29
** (CompileError) config/prod.exs:29: undefined function config/0 (there is no such import)

running build

Anybody know why this config is buggy?
Is there any issue in prod.exs template?

**Comment by clone1018** [comment]
This should be resolved now as per our Discord conversation.
