### ISSUE TITLE
Duplicate emotes showing in some channels

### ISSUE THREAD

**Issue by Ribenaberri** [Glimesh/glimesh.tv#868]
![image](https://user-images.githubusercontent.com/77231604/193131533-f7b95efa-e7c2-4ce1-b680-b2af6dd16fe1.png)

Emotes are showing as pairs of the same emote. So far as I can tell this is at present only effecting myself, and only in one specific channel. I have been unable to find a way to replicate this in any other channel, and I have seen no other reports of this happening (have tried to duplicate this outcome with others but have been unable too) - does not seem to be related to hosting status or subscription status. 

Interestingly, the emote which is not duplicated inititally *was* until the channel made it a subscription only emote, at which point one of these emotes disappeared (I am subscribed in this channel, so seeing the subscription emote is to be expected)

Tried completely logging out and logging in again with no effect, and tried differing browsers to rule out any browser issues. 

Having conferred with clone on the issue it would appear to be an application bug. 

Main issue being faced is being unable to replicate this to try and isolate what the cause may be, and why this is happening in only one channel - despite conditions the same recreated in other channels in terms of moderation, subscription and follower status.

**Comment by blitzkriegmeph** [comment]
Duplicating emotes happening to me in SwedishDemon's channel today


![image](https://user-images.githubusercontent.com/76501699/194562012-9800a1dd-7729-464b-8943-4abc935abae9.png)

**Comment by Ribenaberri** [comment]
#872 

This should be the fix here :)

**Comment by Ribenaberri** [comment]
https://github.com/Glimesh/glimesh.tv/pull/899 final fix for this here. now closing the issue. :)
